# Generated by Django 4.2.16 on 2024-12-24 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_favoriteword_learning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteword',
            name='learning_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 24, 11, 24, 51, 829590, tzinfo=datetime.timezone.utc)),
        ),
    ]
